import 'package:solufine/core/di/auth_di.dart';
import 'package:solufine/core/di/collection_di.dart';
import 'package:solufine/core/di/collection_list_di.dart';
import 'package:solufine/core/di/collection_target_di.dart';
import 'package:solufine/core/di/crop_schedule_di.dart';
import 'package:solufine/core/di/dealer_di.dart';
import 'package:solufine/core/di/dispatch_di.dart';
import 'package:solufine/core/di/dealer_viist_add_di.dart';
import 'package:solufine/core/di/employee_activity_report_di.dart';
import 'package:solufine/core/di/employee_output_di.dart';
import 'package:solufine/core/di/enquiry_di.dart';
import 'package:solufine/core/di/expense_di.dart';
import 'package:solufine/core/di/farmer_di.dart';
import 'package:solufine/core/di/followup_di.dart';
import 'package:solufine/core/di/gallery_di.dart';
import 'package:solufine/core/di/home_di.dart';
import 'package:solufine/core/di/leave_list_di.dart';
import 'package:solufine/core/di/my_expense_di.dart';
import 'package:solufine/core/di/not_visited_dealer_di.dart';
import 'package:solufine/core/di/notification_di.dart';
import 'package:solufine/core/di/place_order_target_di.dart';
import 'package:solufine/core/di/product_di.dart';
import 'package:solufine/core/di/sales_return_di.dart';
import 'package:solufine/core/di/sales_target_di.dart';
import 'package:solufine/core/di/order_history_di.dart';
import 'package:solufine/core/di/product_di.dart';
import 'package:solufine/core/di/sales_return_history_di.dart';

import 'package:solufine/core/di/scheme_di.dart';
import 'package:solufine/core/di/social_media_di.dart';
import 'package:solufine/core/di/team_expense_di.dart';
import 'package:solufine/core/di/team_leave_di.dart';
import 'package:solufine/core/di/top_ten_dealer_di.dart';
import 'package:solufine/core/di/visit_report_di.dart';
import 'package:get_it/get_it.dart';

final sl = GetIt.instance;

Future<void> initGlobalDi() async {
  await initAuthDi();
  await initHomeDi();

  await initFarmerDi();
  await initGalleryDi();
  await initSchemeDi();
  await initDealerDi();
  await initEmployeeActivityDi();
  await initVisitReportDi();
  await initEmployeeOutputDi();
  await initNotificationDi();
  await initLeaveListDi();
  await initTopTenDealerDi();
  await initSocialMediaDi();
  await initTeamLeaveDi();
  await initAddDealerVisitDi();
  await initCollectionWiseFormDi();
  await initNotVisitedDealerDi();
  await initProductDi();
  await initCollectionListDi();
  await initDealerTargetDi();
  await initCropScheduleDi();
  await initMyExpenseFeature();
  await initTeamExpenseFeature();
  await initSalesTargetDi();
  await initPlaceOrderTargetDi();
  await initSalesReturnDi();
  await initOrderHistoryDi();
  await initDispatchDi();
  await initSalesReturnHistoryDi();
  await initExpenseDi();
  await initFollowupDi();
  await initEnquiryDi() ;
}
